---

- hosts: all
  gather_facts: yes
  become: true

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install packages.
      apt: 
        name: ['software-properties-common','module-assistant','linux-headers-amd64']
        state: latest
    
    - name: Apt dist-upgrade
      shell: apt-get dist-upgrade
      become: yes
      args:
        warn: no

    # - name: Install linux headers
    #   shell: apt-get install linux-headers-"$(uname -r)"
    #   become: yes
    #   args:
    #     warn: no

# Fin.
